### ISSUE TITLE
未用过的邀请码填写后报告次数已耗尽

### ISSUE THREAD

**Issue by palxex** [povsister/Go-bh3-VisualNovel#1]
额一不小心就发出去了- -
最近入坑，想完成一下相关成就，于是找到了您这个工具。上个月找到的但是当时似乎域名解析有点问题，今天发现能用了于是想实验一下，结果填写PY码这一步一直过不去。想问一下这里是应该填什么？填写UID和好友那里的邀请码都有问题，报「PY码无效，或次数已用尽」。邀请码本身一次都没用过。 
相关数据已存放至https://gist.github.com/palxex/93141b185de90fb240934b658fd6a993

**Comment by Einsfier** [comment]
emm 这个码不是游戏内的任何码，是我为了防止服务被滥用自行设置的一个限制条件。
获取方式是我在某些渠道公布的可以定期反复使用的码，或者是和我本人索要的定制次数的码。
anyway，感谢first issue，居然有人会看这个稀烂的项目。 。
送上一个可以使用三次的py码，就是你本人的id `palxex`，填入py码字段提交就行了。

**Comment by palxex** [comment]
原来是这样，想当然了。找了下原帖里就有这个码，这眼神-_-|||
个人并没用过golang（Web方向大块投河，尤其是后端），所以代码其实是看不懂的- - 建议（如果不是太麻烦的话）干脆放个让用户自建的教程链接，以减轻服务器负担？
已提交，等任务自动完成。
非常感谢您的这个项目！

**Comment by Einsfier** [comment]
> 个人并没用过golang（Web方向大块投河，尤其是后端），所以代码其实是看不懂的- - 建议（如果不是太麻烦的话）干脆放个让用户自建的教程链接，以减轻服务器负担？

这个项目只是个daemon server，提供restapi供网站后端使用。而且由于是我用golang写的第一个项目，现在看来有大堆的问题。。自建基本不可能，太麻烦了。
